import type { Metadata } from "next";
import "./globals.css";
import Layout from "@/Components/Layout/Layout";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
      >
        <Layout>
        {children}
        </Layout>
      </body>
    </html>
  );
}
